# Generated by Django 6.1.1

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('organizations', '0001_initial'),
        ('providers', '0003_milestone3_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('queue_date', models.DateField(db_index=True, verbose_name='queue date')),
                ('token_number', models.PositiveIntegerField(verbose_name='token number')),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('CALLED', 'Called'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], db_index=True, default='WAITING', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('called_at', models.DateTimeField(blank=True, null=True, verbose_name='called at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('skipped_at', models.DateTimeField(blank=True, null=True, verbose_name='skipped at')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='appointments.appointment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='organizations.organization')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='providers.providerprofile')),
            ],
            options={
                'verbose_name': 'queue entry',
                'verbose_name_plural': 'queue entries',
                'ordering': ['token_number'],
                'indexes': [
                    models.Index(fields=['provider', 'queue_date'], name='queue_provider_date_idx'),
                    models.Index(fields=['provider', 'queue_date', 'status'], name='queue_provider_date_status_idx'),
                    models.Index(fields=['organization', 'queue_date'], name='queue_org_date_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('provider', 'queue_date', 'token_number'), name='unique_provider_date_token'),
                    models.CheckConstraint(condition=models.Q(('token_number__gt', 0)), name='queue_token_positive'),
                ],
            },
        ),
    ]
