# Generated by Django 6.1.1 on 2026-09-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_options_and_more'),
        ('organizations', '0007_alter_organization_industry_type'),
        ('providers', '0006_providerprofile_certifications_and_more'),
        ('queue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queueentry',
            options={'ordering': ['serial_number', 'token_number'], 'verbose_name': 'queue entry', 'verbose_name_plural': 'queue entries'},
        ),
        migrations.AddField(
            model_name='queueentry',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='checked in at'),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='is_checked_in',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is checked in'),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='is urgent'),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='readiness_state',
            field=models.CharField(choices=[('NOT_YET', 'Not yet'), ('GET_READY', 'Get ready'), ('BE_READY', 'Be ready'), ('TURN_NOW', 'Turn now')], default='NOT_YET', max_length=20, verbose_name='readiness state'),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='serial number'),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='urgent_reason',
            field=models.TextField(blank=True, verbose_name='urgent reason'),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='token_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='token number'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['provider', 'queue_date', 'serial_number'], name='queue_prov_date_serial_idx'),
        ),
    ]
