# Generated by Django 6.1.1 on 2026-09-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0002_alter_queueentry_options_queueentry_checked_in_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueentry',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('CALLED', 'Called'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show')], db_index=True, default='WAITING', max_length=20, verbose_name='status'),
        ),
    ]
