# Generated by Django 6.1.1 on 2026-09-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_unique_provider_date_serial'),
        ('organizations', '0007_alter_organization_industry_type'),
        ('providers', '0006_providerprofile_certifications_and_more'),
        ('queue', '0003_alter_queueentry_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.UniqueConstraint(fields=('provider', 'queue_date', 'serial_number'), name='unique_provider_queue_date_serial'),
        ),
    ]
