# Generated by Django 6.1.1 on 2026-10-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0004_queueentry_unique_provider_queue_date_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueentry',
            name='readiness_state',
            field=models.CharField(choices=[('NOT_YET', 'Not yet'), ('GET_READY', 'Get ready'), ('BE_READY', 'Be ready'), ('TURN_NOW', 'Turn now'), ('IN_SERVICE', 'In service')], default='NOT_YET', max_length=20, verbose_name='readiness state'),
        ),
    ]
