# Generated by Django 6.1.1 on 2026-09-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('APPOINTMENT_BOOKED', 'Appointment booked'), ('APPOINTMENT_CANCELLED', 'Appointment cancelled'), ('APPOINTMENT_CHECKED_IN', 'Appointment checked in'), ('QUEUE_CALLED', 'Queue called'), ('QUEUE_SKIPPED', 'Queue skipped'), ('SERVICE_COMPLETED', 'Service completed'), ('PROVIDER_NEW_APPOINTMENT', 'New appointment assigned'), ('PROVIDER_APPOINTMENT_CANCELLED', 'Appointment cancelled'), ('PROVIDER_CHECKED_IN', 'Customer checked in')], db_index=True, max_length=40),
        ),
    ]
