# Generated by Django 6.1.1 on 2026-09-21 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('organizations', '0007_alter_organization_industry_type'),
        ('providers', '0006_providerprofile_certifications_and_more'),
        ('services', '0003_category_service_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date', 'serial_number', 'start_datetime'], 'verbose_name': 'appointment', 'verbose_name_plural': 'appointments'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='appointment date'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='arrival_type',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('WALK_IN', 'Walk-in')], default='SCHEDULED', max_length=20, verbose_name='arrival type'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='booking_channel',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('PHONE', 'Phone'), ('FRONT_DESK', 'Front Desk')], default='ONLINE', max_length=20, verbose_name='booking channel'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='serial number'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['provider', 'appointment_date', 'serial_number'], name='appt_provider_date_serial_idx'),
        ),
    ]
