# Generated by Django 6.1.1 on 2026-09-21 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_options_and_more'),
        ('organizations', '0007_alter_organization_industry_type'),
        ('providers', '0006_providerprofile_certifications_and_more'),
        ('services', '0003_category_service_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('provider', 'appointment_date', 'serial_number'), name='unique_provider_date_serial'),
        ),
    ]
