# Generated by Django 6.1.1 on 2026-10-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_unique_provider_date_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booked_service_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='contact_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
