# Generated by Django 6.1.1 on 2026-10-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_category_service_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='detailed_description',
            field=models.TextField(blank=True, verbose_name='detailed description'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.URLField(blank=True, max_length=500, verbose_name='service image url'),
        ),
        migrations.AddField(
            model_name='service',
            name='important_information',
            field=models.JSONField(blank=True, default=list, verbose_name='important information'),
        ),
        migrations.AddField(
            model_name='service',
            name='preparation_notes',
            field=models.JSONField(blank=True, default=list, verbose_name='preparation notes / requirements'),
        ),
        migrations.AddField(
            model_name='service',
            name='process_steps',
            field=models.JSONField(blank=True, default=list, verbose_name='process steps'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_scope',
            field=models.JSONField(blank=True, default=list, verbose_name='service scope / highlights'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='short description'),
        ),
    ]
