# Generated by Django 6.1.1 on 2026-10-03 20:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_unique_provider_date_serial'),
        ('contact', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentIssueReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('RECEIVED_SERVICE_NOT_UPDATED', 'I received the service, but the appointment was not updated'), ('CHECKED_IN_NOT_SERVED', 'I checked in but was not served'), ('LEFT_BEFORE_CONSULTATION', 'I left before the consultation'), ('OTHER', 'Other issue')], default='CHECKED_IN_NOT_SERVED', max_length=60)),
                ('details', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_reports', to='appointments.appointment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_issue_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment Issue Report',
                'verbose_name_plural': 'Appointment Issue Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
