# Generated by Django 6.1.1 on 2026-09-12 13:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
            ],
            options={
                'verbose_name': 'schedule break',
                'verbose_name_plural': 'schedule breaks',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='day of week')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('is_working_day', models.BooleanField(default=True, verbose_name='working day')),
            ],
            options={
                'verbose_name': 'weekly schedule',
                'verbose_name_plural': 'weekly schedules',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='title')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to='organizations.organizationmembership')),
            ],
            options={
                'verbose_name': 'provider profile',
                'verbose_name_plural': 'provider profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='start datetime')),
                ('end_datetime', models.DateTimeField(verbose_name='end datetime')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='providers.providerprofile')),
            ],
            options={
                'verbose_name': 'provider leave',
                'verbose_name_plural': 'provider leaves',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='custom duration (minutes)')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='custom price')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_services', to='providers.providerprofile')),
            ],
            options={
                'verbose_name': 'provider service',
                'verbose_name_plural': 'provider services',
            },
        ),
    ]
