# Generated by Django 6.1.1 on 2026-09-12 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_services', to='services.service'),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='providers.providerprofile'),
        ),
        migrations.AddField(
            model_name='schedulebreak',
            name='weekly_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='providers.weeklyschedule'),
        ),
        migrations.AddConstraint(
            model_name='providerservice',
            constraint=models.UniqueConstraint(fields=('provider', 'service'), name='unique_provider_service'),
        ),
        migrations.AddConstraint(
            model_name='weeklyschedule',
            constraint=models.UniqueConstraint(fields=('provider', 'day_of_week'), name='unique_provider_schedule_day'),
        ),
        migrations.AddConstraint(
            model_name='weeklyschedule',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='schedule_end_after_start'),
        ),
    ]
