# Generated by Django 6.1.1 on 2026-09-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='providerleave',
            index=models.Index(fields=['provider', 'start_datetime'], name='provider_leave_start_idx'),
        ),
        migrations.AddIndex(
            model_name='providerleave',
            index=models.Index(fields=['provider', 'end_datetime'], name='provider_leave_end_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerleave',
            constraint=models.CheckConstraint(condition=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='leave_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='providerservice',
            constraint=models.CheckConstraint(condition=models.Q(('custom_price__isnull', True), ('custom_price__gte', 0), _connector='OR'), name='provider_service_custom_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='schedulebreak',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='break_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='weeklyschedule',
            constraint=models.CheckConstraint(condition=models.Q(('day_of_week__gte', 0), ('day_of_week__lte', 6)), name='schedule_day_of_week_range'),
        ),
    ]
