# Generated by Django 6.1.1 on 2026-09-16 09:32

import apps.organizations.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_milestone3_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='application_status',
            field=models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20, verbose_name='application status'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='application_status',
            field=models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='INCOMPLETE', max_length=20, verbose_name='application status'),
        ),
        migrations.CreateModel(
            name='ProviderDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('GOVT_ID', 'Government Issued ID'), ('PROFESSIONAL_LICENSE', 'Professional License'), ('CERTIFICATE', 'Degree / Certificate'), ('OTHER', 'Other Supporting Document')], max_length=40)),
                ('file', models.FileField(upload_to='provider_docs/%Y/%m/', validators=[apps.organizations.validators.validate_document_file])),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('provider_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='providers.providerprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_provider_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'provider document',
                'verbose_name_plural': 'provider documents',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['provider_profile', 'status'], name='prov_doc_profile_status_idx')],
            },
        ),
    ]
