# Generated by Django 6.1.1 on 2026-09-16 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_providerprofile_application_status_providerdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='application_rejection_reason',
            field=models.TextField(blank=True, verbose_name='application rejection reason'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='application_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='application reviewed at'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='application_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_provider_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
