# Generated by Django 6.1.1 on 2026-09-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_providerprofile_application_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='certifications',
            field=models.JSONField(blank=True, default=list, verbose_name='certifications'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='education',
            field=models.JSONField(blank=True, default=list, verbose_name='education'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='experience_history',
            field=models.JSONField(blank=True, default=list, verbose_name='experience history'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, verbose_name='years of experience'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='profile_photo',
            field=models.URLField(blank=True, max_length=500, verbose_name='profile photo url'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='specialties',
            field=models.JSONField(blank=True, default=list, verbose_name='specialties'),
        ),
    ]
