# Generated by Django 6.1.1 on 2026-09-16 09:32

import apps.organizations.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='verification_status',
            field=models.CharField(choices=[('SETUP_INCOMPLETE', 'Setup Incomplete'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='APPROVED', max_length=20, verbose_name='verification status'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='verification_status',
            field=models.CharField(choices=[('SETUP_INCOMPLETE', 'Setup Incomplete'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='SETUP_INCOMPLETE', max_length=20, verbose_name='verification status'),
        ),
        migrations.CreateModel(
            name='OrganizationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('BUSINESS_LICENSE', 'Business / Trade License'), ('TAX_CERTIFICATE', 'Tax / TIN Certificate'), ('FACILITY_PERMIT', 'Health / Operational Permit'), ('OTHER', 'Other Supporting Document')], max_length=40)),
                ('file', models.FileField(upload_to='organization_docs/%Y/%m/', validators=[apps.organizations.validators.validate_document_file])),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organizations.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_organization_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'organization document',
                'verbose_name_plural': 'organization documents',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='org_doc_org_status_idx')],
            },
        ),
    ]
