# Generated by Django 6.1.1 on 2026-09-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organizationinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, verbose_name='cover image url'),
        ),
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='industry_type',
            field=models.CharField(choices=[('HEALTHCARE', 'Healthcare & Medical'), ('LEGAL', 'Legal & Law Firm'), ('BEAUTY', 'Beauty, Salon & Wellness'), ('REPAIR', 'Technical Repair & Service'), ('CONSULTING', 'Consulting & Professional Services'), ('OTHER', 'Other Services')], default='HEALTHCARE', max_length=30, verbose_name='industry type'),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.URLField(blank=True, max_length=500, verbose_name='logo url'),
        ),
    ]
