# Generated by Django 6.1.1 on 2026-09-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_backfill_industry_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='industry_type',
            field=models.CharField(choices=[('HEALTHCARE', 'Healthcare & Medical'), ('LEGAL', 'Legal & Law Firm'), ('BEAUTY', 'Beauty, Salon & Wellness'), ('REPAIR', 'Technical Repair & Service'), ('CONSULTING', 'Consulting & Professional Services'), ('OTHER', 'Other Services')], default='OTHER', max_length=30, verbose_name='industry type'),
        ),
    ]
