# Generated by Django 6.1.1 on 2026-10-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_alter_organization_industry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, verbose_name='tagline / motto'),
        ),
    ]
