# Generated by Django 6.1.1 on 2026-10-05 08:10

import apps.organizations.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_organization_tagline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_type', models.CharField(choices=[('BUSINESS_REGISTRATION', 'Business / Trade Registration'), ('OPERATING_LICENSE', 'Operating / Facility License'), ('PROFESSIONAL_ACCREDITATION', 'Professional Accreditation'), ('TAX_REGISTRATION', 'Tax / TIN Registration'), ('OTHER', 'Other Official Credential')], default='BUSINESS_REGISTRATION', max_length=40)),
                ('credential_name', models.CharField(max_length=255, verbose_name='credential name')),
                ('credential_number', models.CharField(blank=True, max_length=100, verbose_name='credential number / license ID')),
                ('issuing_authority', models.CharField(blank=True, max_length=255, verbose_name='issuing authority / board')),
                ('issued_date', models.DateField(blank=True, null=True, verbose_name='issued date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='expiry date')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('document', models.FileField(blank=True, null=True, upload_to='org_credentials/%Y/%m/', validators=[apps.organizations.validators.validate_document_file])),
                ('is_public', models.BooleanField(default=True, verbose_name='display publicly')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='organizations.organization')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_organization_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'organization credential',
                'verbose_name_plural': 'organization credentials',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'verification_status', 'is_public'], name='org_cred_pub_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationOperatingHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'organization operating hours',
                'verbose_name_plural': 'organization operating hours',
                'ordering': ['day_of_week'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'day_of_week'), name='unique_org_day_operating_hours')],
            },
        ),
    ]
